"use client";

import React, { useState, useEffect } from 'react';
import { useParams } from 'next/navigation';

import { Word } from '@/app/components/WordTable';
import { WordTable } from '@/app/components/WordTable';
import { WordInfo } from '@/app/components/WordInfo';

const words: Word[] = [
  { id: 11, term: 'improve', type: 'verb', tags: ['plan', 'modify'] },
  { id: 12, term: 'differentiate', type: 'verb', tags: ['maintain', 'validate'] },
  { id: 13, term: 'arrange', type: 'verb', tags: ['reorganize', 'reflect'] },
  { id: 14, term: 'implement', type: 'verb', tags: ['select', 'evaluate'] },
  { id: 15, term: 'adapt', type: 'verb', tags: ['define', 'understand'] },
  { id: 16, term: 'contribute', type: 'verb', tags: ['revise', 'complete'] },
  { id: 17, term: 'modify', type: 'verb', tags: ['arrange', 'translate'] },
  { id: 18, term: 'operate', type: 'verb', tags: ['introduce', 'represent'] },
  { id: 19, term: 'differentiate', type: 'verb', tags: ['include', 'realize'] },
  { id: 20, term: 'synthesize', type: 'verb', tags: ['enhance', 'provide'] },
  { id: 21, term: 'organize', type: 'verb', tags: ['research', 'plan'] },
  { id: 22, term: 'construct', type: 'verb', tags: ['assign', 'propose'] },
  { id: 23, term: 'research', type: 'verb', tags: ['demonstrate', 'initiate'] },
  { id: 24, term: 'submit', type: 'verb', tags: ['categorize', 'implement'] },
  { id: 25, term: 'optimize', type: 'verb', tags: ['summarize', 'translate'] },
  { id: 26, term: 'express', type: 'verb', tags: ['integrate', 'construct'] },
  { id: 27, term: 'modify', type: 'verb', tags: ['provide', 'display'] },
  { id: 28, term: 'monitor', type: 'verb', tags: ['differentiate', 'investigate'] },
  { id: 29, term: 'modify', type: 'verb', tags: ['facilitate', 'report'] },
  { id: 30, term: 'identify', type: 'verb', tags: ['identify', 'realize'] },
  { id: 31, term: 'include', type: 'verb', tags: ['operate', 'analyze'] },
  { id: 32, term: 'emphasize', type: 'verb', tags: ['develop', 'introduce'] },
  { id: 33, term: 'manage', type: 'verb', tags: ['structure', 'compose'] },
  { id: 34, term: 'provide', type: 'verb', tags: ['demonstrate', 'examine'] },
  { id: 35, term: 'design', type: 'verb', tags: ['structure', 'solve'] },
  { id: 36, term: 'maximize', type: 'verb', tags: ['modify', 'reassess'] },
  { id: 37, term: 'compose', type: 'verb', tags: ['simplify', 'realize'] },
  { id: 38, term: 'simplify', type: 'verb', tags: ['compile', 'recommend'] },
  { id: 39, term: 'analyze', type: 'verb', tags: ['integrate', 'compile'] },
  { id: 40, term: 'summarize', type: 'verb', tags: ['analyze', 'formulate'] },
  { id: 41, term: 'recommend', type: 'verb', tags: ['initiate', 'assign'] },
  { id: 42, term: 'translate', type: 'verb', tags: ['summarize', 'compose'] },
  { id: 43, term: 'plan', type: 'verb', tags: ['select', 'pursue'] },
  { id: 44, term: 'balance', type: 'verb', tags: ['validate', 'document'] },
  { id: 45, term: 'execute', type: 'verb', tags: ['complete', 'understand'] },
  { id: 46, term: 'summarize', type: 'verb', tags: ['prepare', 'emphasize'] },
  { id: 47, term: 'consider', type: 'verb', tags: ['resolve', 'prioritize'] },
  { id: 48, term: 'refine', type: 'verb', tags: ['reorganize', 'maintain'] },
  { id: 49, term: 'execute', type: 'verb', tags: ['submit', 'summarize'] },
  { id: 50, term: 'research', type: 'verb', tags: ['schedule', 'prepare'] },
  { id: 51, term: 'schedule', type: 'verb', tags: ['balance', 'update'] },
  { id: 52, term: 'solve', type: 'verb', tags: ['structure', 'manage'] },
  { id: 53, term: 'advance', type: 'verb', tags: ['categorize', 'compile'] },
  { id: 54, term: 'translate', type: 'verb', tags: ['produce', 'provide'] },
  { id: 55, term: 'interpret', type: 'verb', tags: ['summarize', 'represent'] },
  { id: 56, term: 'introduce', type: 'verb', tags: ['revise', 'connect'] },
  { id: 57, term: 'observe', type: 'verb', tags: ['update', 'support'] },
  { id: 58, term: 'propose', type: 'verb', tags: ['strategize', 'reflect'] },
  { id: 59, term: 'evaluate', type: 'verb', tags: ['discuss', 'organize'] },
  { id: 60, term: 'document', type: 'verb', tags: ['perform', 'introduce'] },
  { id: 61, term: 'calculate', type: 'verb', tags: ['understand', 'generate'] },
  { id: 62, term: 'summarize', type: 'verb', tags: ['analyze', 'execute'] },
  { id: 63, term: 'revise', type: 'verb', tags: ['optimize', 'differentiate'] },
  { id: 64, term: 'submit', type: 'verb', tags: ['understand', 'synthesize'] },
  { id: 65, term: 'integrate', type: 'verb', tags: ['emphasize', 'pursue'] },
  { id: 66, term: 'strategize', type: 'verb', tags: ['optimize', 'calculate'] },
  { id: 67, term: 'reorganize', type: 'verb', tags: ['deliver', 'represent'] },
  { id: 68, term: 'operate', type: 'verb', tags: ['facilitate', 'translate'] },
  { id: 69, term: 'synthesize', type: 'verb', tags: ['pursue', 'include'] },
  { id: 70, term: 'negotiate', type: 'verb', tags: ['represent', 'arrange'] },
  { id: 71, term: 'execute', type: 'verb', tags: ['enhance', 'synthesize'] },
  { id: 72, term: 'suggest', type: 'verb', tags: ['advance', 'reassess'] },
  { id: 73, term: 'calculate', type: 'verb', tags: ['arrange', 'reflect'] },
  { id: 74, term: 'negotiate', type: 'verb', tags: ['simplify', 'discuss'] },
  { id: 75, term: 'facilitate', type: 'verb', tags: ['connect', 'revise'] },
  { id: 76, term: 'evaluate', type: 'verb', tags: ['emphasize', 'pursue'] },
  { id: 77, term: 'modify', type: 'verb', tags: ['calculate', 'propose'] },
  { id: 78, term: 'observe', type: 'verb', tags: ['outline', 'solve'] },
  { id: 79, term: 'resolve', type: 'verb', tags: ['observe', 'improve'] },
  { id: 80, term: 'research', type: 'verb', tags: ['investigate', 'pursue'] },
  { id: 81, term: 'improve', type: 'verb', tags: ['categorize', 'verify'] },
  { id: 82, term: 'maintain', type: 'verb', tags: ['observe', 'edit'] },
  { id: 83, term: 'reorganize', type: 'verb', tags: ['differentiate', 'suggest'] },
  { id: 84, term: 'upgrade', type: 'verb', tags: ['propose', 'research'] },
  { id: 85, term: 'reflect', type: 'verb', tags: ['refine', 'design'] },
  { id: 86, term: 'complete', type: 'verb', tags: ['realize', 'publish'] },
  { id: 87, term: 'translate', type: 'verb', tags: ['design', 'calculate'] },
  { id: 88, term: 'understand', type: 'verb', tags: ['modify', 'emphasize'] },
  { id: 89, term: 'differentiate', type: 'verb', tags: ['propose', 'understand'] },
  { id: 90, term: 'structure', type: 'verb', tags: ['deliver', 'design'] },
  { id: 91, term: 'balance', type: 'verb', tags: ['understand', 'connect'] },
  { id: 92, term: 'reassess', type: 'verb', tags: ['interpret', 'integrate'] },
  { id: 93, term: 'prepare', type: 'verb', tags: ['implement', 'enhance'] },
  { id: 94, term: 'prioritize', type: 'verb', tags: ['complete', 'review'] },
  { id: 95, term: 'suggest', type: 'verb', tags: ['include', 'document'] },
  { id: 96, term: 'display', type: 'verb', tags: ['initiate', 'demonstrate'] },
  { id: 97, term: 'operate', type: 'verb', tags: ['maximize', 'reassess'] },
  { id: 98, term: 'display', type: 'verb', tags: ['recommend', 'adapt'] },
  { id: 99, term: 'visualize', type: 'verb', tags: ['contribute', 'validate'] },
  { id: 100, term: 'pursue', type: 'verb', tags: ['collaborate', 'develop'] },
  { id: 101, term: 'integrate', type: 'verb', tags: ['manage', 'revise'] },
  { id: 102, term: 'complete', type: 'verb', tags: ['connect', 'reassess'] },
  { id: 103, term: 'balance', type: 'verb', tags: ['understand', 'update'] },
  { id: 104, term: 'explore', type: 'verb', tags: ['arrange', 'perform'] },
  { id: 105, term: 'examine', type: 'verb', tags: ['perform', 'monitor'] },
  { id: 106, term: 'analyze', type: 'verb', tags: ['collaborate', 'summarize'] },
  { id: 107, term: 'implement', type: 'verb', tags: ['synthesize', 'select'] },
  { id: 108, term: 'integrate', type: 'verb', tags: ['enhance', 'modify'] },
  { id: 109, term: 'differentiate', type: 'verb', tags: ['design', 'compose'] },
  { id: 110, term: 'develop', type: 'verb', tags: ['integrate', 'refine'] },
  { id: 111, term: 'identify', type: 'verb', tags: ['calculate', 'pursue'] },
  { id: 112, term: 'edit', type: 'verb', tags: ['explore', 'prepare'] },
  { id: 113, term: 'compose', type: 'verb', tags: ['structure', 'organize'] },
  { id: 114, term: 'investigate', type: 'verb', tags: ['refine', 'generate'] },
  { id: 115, term: 'document', type: 'verb', tags: ['develop', 'investigate'] },
  { id: 116, term: 'outline', type: 'verb', tags: ['manage', 'submit'] },
  { id: 117, term: 'refine', type: 'verb', tags: ['select', 'strategize'] },
  { id: 118, term: 'document', type: 'verb', tags: ['enhance', 'synthesize'] },
  { id: 119, term: 'enhance', type: 'verb', tags: ['support', 'review'] },
  { id: 120, term: 'evaluate', type: 'verb', tags: ['prioritize', 'reorganize'] },
  { id: 121, term: 'formulate', type: 'verb', tags: ['enhance', 'create'] },
  { id: 122, term: 'connect', type: 'verb', tags: ['differentiate', 'compile'] },
  { id: 123, term: 'demonstrate', type: 'verb', tags: ['examine', 'define'] },
  { id: 124, term: 'visualize', type: 'verb', tags: ['reorganize', 'advance'] },
  { id: 125, term: 'prioritize', type: 'verb', tags: ['design', 'evaluate'] },
  { id: 126, term: 'record', type: 'verb', tags: ['update', 'maintain'] },
  { id: 127, term: 'explore', type: 'verb', tags: ['pursue', 'compile'] },
  { id: 128, term: 'calculate', type: 'verb', tags: ['collaborate', 'improve'] },
  { id: 129, term: 'assign', type: 'verb', tags: ['summarize', 'execute'] },
  { id: 130, term: 'verify', type: 'verb', tags: ['structure', 'consider'] },
  { id: 131, term: 'prioritize', type: 'verb', tags: ['compose', 'submit'] },
  { id: 132, term: 'develop', type: 'verb', tags: ['plan', 'compose'] },
  { id: 133, term: 'analyze', type: 'verb', tags: ['facilitate', 'differentiate'] },
  { id: 134, term: 'generate', type: 'verb', tags: ['reorganize', 'evaluate'] },
  { id: 135, term: 'advance', type: 'verb', tags: ['contribute', 'adapt'] },
  { id: 136, term: 'reassess', type: 'verb', tags: ['execute', 'optimize'] },
  { id: 137, term: 'differentiate', type: 'verb', tags: ['differentiate', 'connect'] },
  { id: 138, term: 'develop', type: 'verb', tags: ['facilitate', 'observe'] },
  { id: 139, term: 'update', type: 'verb', tags: ['suggest', 'modify'] },
  { id: 140, term: 'analyze', type: 'verb', tags: ['maximize', 'synthesize'] },
  { id: 141, term: 'adapt', type: 'verb', tags: ['verify', 'select'] },
  { id: 142, term: 'visualize', type: 'verb', tags: ['synthesize', 'analyze'] },
  { id: 143, term: 'submit', type: 'verb', tags: ['interpret', 'integrate'] },
  { id: 144, term: 'strategize', type: 'verb', tags: ['generate', 'construct'] },
  { id: 145, term: 'consider', type: 'verb', tags: ['deliver', 'compile'] },
  { id: 146, term: 'structure', type: 'verb', tags: ['complete', 'formulate'] },
  { id: 147, term: 'interpret', type: 'verb', tags: ['document', 'strategize'] },
  { id: 148, term: 'refine', type: 'verb', tags: ['visualize', 'explore'] },
  { id: 149, term: 'define', type: 'verb', tags: ['adapt', 'perform'] },
  { id: 150, term: 'evaluate', type: 'verb', tags: ['publish', 'prepare'] },
  { id: 151, term: 'plan', type: 'verb', tags: ['select', 'display'] },
  { id: 152, term: 'arrange', type: 'verb', tags: ['record', 'produce'] },
  { id: 153, term: 'review', type: 'verb', tags: ['discuss', 'pursue'] },
  { id: 154, term: 'plan', type: 'verb', tags: ['refine', 'contribute'] },
  { id: 155, term: 'verify', type: 'verb', tags: ['visualize', 'consider'] },
  { id: 156, term: 'edit', type: 'verb', tags: ['modify', 'support'] },
  { id: 157, term: 'review', type: 'verb', tags: ['examine', 'arrange'] },
  { id: 158, term: 'evaluate', type: 'verb', tags: ['develop', 'integrate'] },
  { id: 159, term: 'design', type: 'verb', tags: ['initiate', 'differentiate'] },
  { id: 160, term: 'refine', type: 'verb', tags: ['execute', 'publish'] },
  { id: 161, term: 'simplify', type: 'verb', tags: ['connect', 'express'] },
  { id: 162, term: 'display', type: 'verb', tags: ['categorize', 'validate'] },
  { id: 163, term: 'recommend', type: 'verb', tags: ['publish', 'reflect'] },
  { id: 164, term: 'outline', type: 'verb', tags: ['prioritize', 'collaborate'] },
  { id: 165, term: 'perform', type: 'verb', tags: ['improve', 'formulate'] },
  { id: 166, term: 'verify', type: 'verb', tags: ['evaluate', 'reorganize'] },
  { id: 167, term: 'display', type: 'verb', tags: ['produce', 'visualize'] },
  { id: 168, term: 'reassess', type: 'verb', tags: ['execute', 'investigate'] },
  { id: 169, term: 'manage', type: 'verb', tags: ['differentiate', 'categorize'] },
  { id: 170, term: 'revise', type: 'verb', tags: ['recommend', 'reassess'] },
  { id: 171, term: 'simplify', type: 'verb', tags: ['manage', 'publish'] },
  { id: 172, term: 'synthesize', type: 'verb', tags: ['enhance', 'connect'] },
  { id: 173, term: 'select', type: 'verb', tags: ['propose', 'record'] },
  { id: 174, term: 'negotiate', type: 'verb', tags: ['perform', 'publish'] },
  { id: 175, term: 'contribute', type: 'verb', tags: ['calculate', 'simplify'] },
  { id: 176, term: 'adapt', type: 'verb', tags: ['maximize', 'categorize'] },
  { id: 177, term: 'produce', type: 'verb', tags: ['advance', 'perform'] },
  { id: 178, term: 'implement', type: 'verb', tags: ['create', 'operate'] },
  { id: 179, term: 'consider', type: 'verb', tags: ['demonstrate', 'refine'] },
  { id: 180, term: 'analyze', type: 'verb', tags: ['validate', 'collaborate'] },
  { id: 181, term: 'contribute', type: 'verb', tags: ['understand', 'complete'] },
  { id: 182, term: 'resolve', type: 'verb', tags: ['simplify', 'translate'] },
  { id: 183, term: 'document', type: 'verb', tags: ['facilitate', 'balance'] },
  { id: 184, term: 'adapt', type: 'verb', tags: ['improve', 'enhance'] },
  { id: 185, term: 'assign', type: 'verb', tags: ['propose', 'formulate'] },
  { id: 186, term: 'reflect', type: 'verb', tags: ['implement', 'propose'] },
  { id: 187, term: 'summarize', type: 'verb', tags: ['submit', 'research'] },
  { id: 188, term: 'reassess', type: 'verb', tags: ['investigate', 'upgrade'] },
  { id: 189, term: 'recommend', type: 'verb', tags: ['complete', 'integrate'] },
  { id: 190, term: 'validate', type: 'verb', tags: ['evaluate', 'understand'] },
  { id: 191, term: 'manage', type: 'verb', tags: ['summarize', 'analyze'] },
  { id: 192, term: 'modify', type: 'verb', tags: ['understand', 'strategize'] },
  { id: 193, term: 'verify', type: 'verb', tags: ['monitor', 'produce'] },
  { id: 194, term: 'compile', type: 'verb', tags: ['collaborate', 'structure'] },
  { id: 195, term: 'facilitate', type: 'verb', tags: ['discuss', 'plan'] },
  { id: 196, term: 'differentiate', type: 'verb', tags: ['complete', 'support'] },
  { id: 197, term: 'operate', type: 'verb', tags: ['collaborate', 'complete'] },
  { id: 198, term: 'manage', type: 'verb', tags: ['compose', 'connect'] },
  { id: 199, term: 'introduce', type: 'verb', tags: ['plan', 'differentiate'] },
  { id: 200, term: 'solve', type: 'verb', tags: ['connect', 'construct'] },
  { id: 201, term: 'balance', type: 'verb', tags: ['display', 'translate'] },
  { id: 202, term: 'assign', type: 'verb', tags: ['connect', 'reassess'] },
  { id: 203, term: 'solve', type: 'verb', tags: ['execute', 'balance'] },
  { id: 204, term: 'develop', type: 'verb', tags: ['maintain', 'enhance'] },
  { id: 205, term: 'verify', type: 'verb', tags: ['investigate', 'interpret'] },
  { id: 206, term: 'examine', type: 'verb', tags: ['implement', 'compile'] },
  { id: 207, term: 'contribute', type: 'verb', tags: ['structure', 'compile'] },
  { id: 208, term: 'translate', type: 'verb', tags: ['categorize', 'execute'] },
  { id: 209, term: 'schedule', type: 'verb', tags: ['compile', 'investigate'] },
  { id: 210, term: 'reassess', type: 'verb', tags: ['enhance', 'schedule'] }
];

const WordPage: React.FC = () => {
  const [selectedWord, setSelectedWord] = useState<Word | null>(null);
  const params = useParams();

useEffect(() => {
  const wordParam = params?.word?.toString();
  if (wordParam && typeof wordParam === 'string') {
    const decoded = decodeURIComponent(wordParam).toLowerCase().trim();
    const match = words.find(w => w.term.toLowerCase() === decoded);
    if (match) {
      setSelectedWord(match);
    }
  }
}, [params?.word]);

  return (
<div className="min-h-screen bg-[#323944] pt-20 p-4 text-white flex flex-col md:flex-row md:justify-start md:items-start max-w-7xl">
      {/* WordTable Component */}
      <WordTable onRowClick={setSelectedWord} /*selectedWord={words[0]}*//>

      {/* Information Display Component */}
      <div className='hidden sm:block md:block'>
        <WordInfo selectedWord={selectedWord} />
      </div>
    </div>
  );
};

export default WordPage;
